version: '3.8'
services:
  api:
    build:
      context: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      - REGION=${REGION}
      - ENVIRONMENT=${ENVIRONMENT}
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - backend
  db:
    build:
      context: ./db
    volumes:
      - ./db/var/pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - backend
networks:
  backend:
    driver: bridge